### ISSUE TITLE
it doesnt seem to work for me

### ISSUE THREAD

**Issue by Beastcollector** [ItsCollector/PetSim99AutoFish#2]
when i press f1 it works with the casting line. after that it takes a really long time to only tap once for the macro. idk what went wrong.

**Comment by Beastcollector** [comment]
i did
my laptop is 1366 x 768 screenresolution. i can send a vid in like 15 minutes of what happens if that helps

**Comment by ItsCollector** [comment]
> i did my laptop is 1366 x 768 screenresolution. i can send a vid in like 15 minutes of what happens if that helps

Start the fishing mini game manually, and press F7. This will tell you if the coordinates are configured, which is what i suspect your issue is

**Comment by Beastcollector** [comment]
it still doesnt work
it also says: white pixel not found, reload the script if you changed it or recapture the coordinates

**Comment by ItsCollector** [comment]
> it still doesnt work it also says: white pixel not found, reload the script if you changed it or recapture the coordinates

It doesn't work because you need to put the coordinates into the script yourself with F6, save and reopen the script.

**Comment by lnno** [comment]
Having the same issue as him.

I've followed the instructions in the readMe. I've deleted the folder and extracted twice now, my resolution is 1920x1080 so I figured I wouldn't even have to configure anything but it will cast, then reel in one item then stop. Or it'll just continuously cast. I changed the coordinates as well and still nothing, weird.

**Comment by mrwyxz** [comment]
> > it still doesnt work it also says: white pixel not found, reload the script if you changed it or recapture the coordinates
> 
> It doesn't work because you need to put the coordinates into the script yourself with F6 to see coordinates of your mouse position, type them into the script, save and reopen the script.

Same for me.

**Comment by ItsCollector** [comment]
> Having the same issue as him.
> 
> I've followed the instructions in the readMe. I've deleted the folder and extracted twice now, my resolution is 1920x1080 so I figured I wouldn't even have to configure anything but it will cast, then reel in one item then stop. Or it'll just continuously cast. I changed the coordinates as well and still nothing, weird.
> 
> Edit - Seems like the config is editing itself even after I've confirmed the coordinates were changed. I even tried editing the coords in the script itself.

The config file dynamically changes as it saves the location of your GUI window, it is not responsible for holding the white pixel coordinates. If you read the ReadMe file it tells you exactly where to put the coordinates.
