### ISSUE TITLE
Doesn't seems to capture white pixel.

### ISSUE THREAD

**Issue by ZeInSoRiTy** [ItsCollector/PetSim99AutoFish#3]
So it just don't really capture white pixel(checking with F7 and just run). Look: 
![image](https://github.com/ItsCollector/PetSim99AutoFish/assets/101979081/d16090e3-6292-4d63-8f27-31616b3aa5c0)
![image](https://github.com/ItsCollector/PetSim99AutoFish/assets/101979081/18a9fb36-7b3a-4bc1-820c-3f1dad13b2a0)
![image](https://github.com/ItsCollector/PetSim99AutoFish/assets/101979081/86b6510f-1b45-480c-9324-ccbaad56807a)
![image](https://github.com/ItsCollector/PetSim99AutoFish/assets/101979081/18efdc22-9d9e-4eb3-a7f6-f552918b030f)
![image](https://github.com/ItsCollector/PetSim99AutoFish/assets/101979081/4f3e5155-0ef4-42c8-a0ff-0efe7adfd584)

**Comment by ItsCollector** [comment]
The config file does not store the pixel check coordinates. If you read the ReadMe file it tells you exactly where to put the coordinates, which is in the script
